# These are supported funding model platforms

# github: [PrismarineTeam, AlphaKR93] # when :(
# open_collective: Prismarine # WIP
patreon: alphakr93_
# issuehunt: alphakr93
ko_fi: alphakr93
custom: ["https://www.paypal.me/alphakr93"]#, "https://toon.at/donate/637349490049950363", "https://www.buymeacoffee.com/alpha93", "TOSS HERE"]
# liberapay: alphakr93
