# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# open_collective: Prismarine # WIP
patreon: alphakr93_
ko_fi: alphakr93
custom: ["https://toon.at/donate/637349490049950363", "https://www.paypal.me/alphakr93"]
