# These are supported funding model platforms

# github: [PrismarineTeam, AlphaKR93]
# open_collective: Prismarine # WIP
patreon: alphakr93_
ko_fi: alphakr93
custom: ["https://www.paypal.me/alphakr93"]#, "https://toon.at/donate/637349490049950363", "TOSS HERE"]
