name: report errors (English)
description: please report errors caused with Prismarine's patches.
labels: ["bug"]
assignees: ["AlphaKR93"]
body:
  - type: markdown
    attributes:
      value: |
        before reporting an error, please make sure that this error is caused in the **latest version** of Prismarine.
        also, please check that this error is not reported.

  - type: input
    attributes:
      label: Spark URL
      description: If you have Spark profile link, please write it down here.
      placeholder: 'TIP: you can get profile link by putting ''/spark profiler --timeout (second that you want to test, e.g 300)''in the server.'
    validations:
      required: false

  - type: textarea
    attributes:
      label: error description
      description: please write every information about errors.
    validations:
      required: true

  - type: textarea
    attributes:
      label: result expectation
      description: please write down how Prismarine worked if error did not occured.
    validations:
      required: true

  - type: textarea
    attributes:
      label: real result
      description: please write down the result that error occured.
      placeholder: |
        TIP: Click here and drag files to upload files.
        File can help Prismarine team to solve the errors.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce errors
      description: Please write down how to reproduce errors.
      placeholder: |
        1. move to '...'.
        2. write down '....'.
        3. choose '....'.
        4. add '....' plugins.
        5. add '....' datapack.
        6. this is how this error occured.
    validations:
      required: true

  - type: textarea
    attributes:
      label: plugin list
      description: write down every plugins that you installed in your server.
      placeholder: |
        you can check the list by writing ''/plugins''.
        If you didn't applied plugins, please write "N/A" !
    validations:
      required: true

  - type: textarea
    attributes:
      label: Datapack list
      description: Please write every datapacks that you installed in your server.
      placeholder: |
        you can check list of datapack by writing''/datapack list''.
        적용한 플러그인이 없을 경우 "없음" 이라고 입력해주세요!
    validations:
      required: true

  - type: input
    attributes:
      label: Prismarine의 버전
      description: Prismarine의 버전을 입력해주세요.
      placeholder: |
        TIP: Prismarine의 버전은 ''/version'' 을 입력하여 확인할 수 있어요.
        예: git-Prismarine-"77f3c4a" (MC: 1.19.1)
    validations:
      required: true

  - type: input
    attributes:
      label: JVM 플래그
      description: Prismarine을 작동할 때 사용한 JVM 플래그를 입력해주세요.
      placeholder: |
        TIP: java -jar 는 필요하지 않아요. 플래그가 없을 경우 "없음"을 입력해주세요!
        예: -Xms8G -Xmx8G -Dterminal.jline=false -Dterminal.ansi=true -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -server
    validations:
      required: true

  - type: textarea
    attributes:
      label: JDK
      description: JDK의 이름과 버전이 무엇인지 입력해주세요.
      placeholder: |
        TIP: JDK의 버전은 터미널(또는 명령 프롬프트)에서 `java -version` 을 입력하여 확인할 수 있어요.
        예시: openjdk version "17.0.3" 2022-04-19
        OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
        OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)
    validations:
      required: true

  - type: input
    attributes:
      label: 운영체제
      description: 서버가 작동한 운영 체제가 무엇인지 입력해주세요.
      placeholder: |
        예: Windows 11 Pro for Workstatin 21H2 (22000.100), Ubuntu 20.04
    validations:
      required: true

  - type: textarea
    attributes:
      label: 추가 정보
      description: 추가적인 정보를 입력할 수 있어요.
      placeholder: 'TIP: 여기를 클릭하고 파일을 드래그하면 파일을 업로드 할 수 있습니다.'
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: 신고하기 전, 다시 한번 확인해주세요.
      description: 
      options:
        - label: 저는 이 Minecraft 버전에서 최신 버전의 Prismarine을 사용하고 있습니다.
        - label: 저는 이 오류가 신고되지 않았음을 확인했습니다.
        - label: 이 버전은 Prismarine에서 지원하는 버전입니다.