name: 서버/스레드 충돌 및 Stacktrace (English)
description: 서버/스레드의 충돌 또는 Stacktrace를 신고하세요.
labels: ["bug"]
assignees: ["AlphaKR93"]
body:
  - type: markdown
    attributes:
      value: |
        오류를 신고하기 전, 이 오류가 Prismarine의 **최신 버전** 에서 발생한 것이 확실한지 확인해주세요.
        또한, 이 오류가 신고되어 있지 않은지 확인해주세요.

  - type: input
    attributes:
      label: Spark URL
      description: Spark 프로필 링크가 있다면 여기에 입력해주세요.
      placeholder: 'TIP: 프로필 링크는 서버에서 ''/spark profiler --timeout (테스트할 초, 예를 들어 300)'' 을 입력하여 얻을 수 있어요.'
    validations:
      required: false

  - type: textarea
    attributes:
      label: 오류 설명
      description: 오류에 대한 모든 정보를 서술해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 충돌 로그 또는 Stacktrace
      description: 충돌 로그 또는 Stacktrace "전문" 을 입력해주세요.
      placeholder: |
        hastebin 또는 로그를 여기에 입력해주세요.

        TIP: 여기를 클릭하고 파일을 드래그하면 파일을 업로드 할 수 있습니다.
        파일은 Prismarine 팀이 오류를 해결하는 데 도움을 줄 수 있습니다.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 오류 재현 방법 (가능한 경우)
      description: 오류를 재현할 수 있는 방법을 서술해주세요.
      placeholder: |
        1. '...' 로 이동합니다.
        2. '....' 를 입력합니다.
        3. '....' 를 선택합니다.
        4. '....' 플러그인을 추가합니다.
        5. '....' 데이터팩을 추가합니다.
        6. 이렇게 하면 오류가 발생합니다.
    validations:
      required: false

  - type: textarea
    attributes:
      label: 플러그인 리스트
      description: 서버에 설치되어있는 모든 플러그인의 리스트를 적어주세요.
      placeholder: |
        /plugins 를 입력하여 플러그인 리스트를 확인할 수 있어요.
        적용한 플러그인이 없을 경우 "없음" 이라고 입력해주세요!
    validations:
      required: true

  - type: textarea
    attributes:
      label: 데이터팩 리스트
      description: 서버에 설치되어있는 모든 데이터팩의 리스트를 적어주세요.
      placeholder: |
        ''/datapack list'' 를 입력하여 데이터팩 리스트를 확인할 수 있어요.
        적용한 플러그인이 없을 경우 "없음" 이라고 입력해주세요!
    validations:
      required: true

  - type: input
    attributes:
      label: Prismarine의 버전
      description: Prismarine의 버전을 입력해주세요.
      placeholder: |
        TIP: Prismarine의 버전은 ''/version'' 을 입력하여 확인할 수 있어요.
        예: git-Prismarine-"77f3c4a" (MC: 1.19.1)
    validations:
      required: true

  - type: input
    attributes:
      label: JVM 플래그
      description: Prismarine을 작동할 때 사용한 JVM 플래그를 입력해주세요.
      placeholder: |
        TIP: java와 -jar ~~.jar 는 필요하지 않아요. 플래그가 없을 경우 "없음"을 입력해주세요!
        예: -Xms8G -Xmx8G -Dterminal.jline=false -Dterminal.ansi=true -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -server
    validations:
      required: true

  - type: textarea
    attributes:
      label: JDK
      description: JDK의 이름과 버전이 무엇인지 입력해주세요.
      placeholder: |
        TIP: JDK의 버전은 터미널(또는 명령 프롬프트)에서 `java -version` 을 입력하여 확인할 수 있어요.
        예시: openjdk version "17.0.3" 2022-04-19
        OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
        OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)
    validations:
      required: true

  - type: input
    attributes:
      label: 운영체제
      description: 서버가 작동한 운영 체제가 무엇인지 입력해주세요.
      placeholder: |
        예: Windows 11 Pro for Workstatin 21H2 (22000.100), Ubuntu 20.04
    validations:
      required: true

  - type: textarea
    attributes:
      label: 추가 정보
      description: 추가적인 정보를 입력할 수 있어요.
      placeholder: 'TIP: 여기를 클릭하고 파일을 드래그하면 파일을 업로드 할 수 있습니다.'
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: 신고하기 전, 다시 한번 확인해주세요.
      description: 
      options:
        - label: 저는 이 Minecraft 버전에서 최신 버전의 Prismarine을 사용하고 있습니다.
        - label: 저는 이 오류가 신고되지 않았음을 확인했습니다.
        - label: 이 버전은 Prismarine에서 지원하는 버전입니다.