name: 기타
description: 분류되어 있지 않은 문제를 신고할 수 있어요.
labels: ["bug"]
assignees: ["AlphaKR93"]
body:
  - type: markdown
    attributes:
      value: |
        오류를 신고하기 전, 이 오류가 이미 신고되어 있지 않은지 확인해주세요.

  - type: textarea
    attributes:
      label: 오류 설명
      description: 오류에 대한 모든 정보를 서술해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 추가 정보
      description: 추가적인 정보를 입력할 수 있어요.
      placeholder: 'TIP: 여기를 클릭하고 파일을 드래그하면 파일을 업로드 할 수 있습니다.'
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: 신고하기 전, 다시 한번 확인해주세요.
      description: 
      options:
        - label: 저는 이 오류가 신고되지 않았음을 확인했습니다.