name: Build Prismarine
on:
  push:
  pull_request:
  workflow_dispatch:
  
env:
  branch: ver/1.18.2
  debug: true
  reobf: true
  mojmap: false
  build: false

jobs:
  release:
    strategy:
      matrix:
        jdk: [17.0.3]
        java: ['temurin']
        os: [ubuntu-20.04]
        master: ['ver/1.18.2']

    if: "!startsWith(github.event.commits[0].message, '[CI-Skip]')"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout action
        uses: actions/checkout@main

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@master

      - name: Set up JDK ${{ matrix.java }} ${{ matrix.jdk }}
        uses: actions/setup-java@main
        with:
          distribution: ${{ matrix.java }}
          java-version: ${{ matrix.jdk }}
          cache: 'gradle'

      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
          echo "workflow=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace

      - name: Build
        if: env.debug != 'true' || env.build == 'true'
        run: ./gradlew build --stacktrace

      - name: Create Reobf Jar
        if: env.debug != 'true' || env.reobf == 'true'
        run: ./gradlew createReobfPaperclipJar --stacktrace

      - name: Create Mojmap Jar
        if: env.debug != 'true' || env.mojmap == 'true'
        run: ./gradlew createMojmapPaperclipJar --stacktrace

      - name: Upload Artifacts
        if: env.debug == 'true'
        uses: actions/upload-artifact@main
        with:
          name: 'Prismarine-Debug'
          path: 'build/libs'

      - name: Release Artifacts
        if: github.ref_name == env.branch
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Release #${{ env.workflow }}"
          automatic_release_tag: release-${{ env.workflow }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: build/libs/*.jar
          prerelease: false
          
      - name: Release Artifacts (Latest)
        if: github.ref_name == env.branch
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Release #${{ env.workflow }}"
          automatic_release_tag: latest
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: build/libs/*.jar
          prerelease: false
